CREATE TABLE IF NOT EXISTS `users` (
	`id` INT UNSIGNED NULL AUTO_INCREMENT,
	`login` VARCHAR(64) NULL DEFAULT NULL,
	`email` VARCHAR(64) NULL DEFAULT NULL,
	`password` VARCHAR(128) NULL DEFAULT NULL,
	INDEX `id_key` (`id`)
)
COLLATE='utf8mb4_general_ci';
